# Generated by Django 4.0.2 on 2022-02-03 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Flexizyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flex_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Monomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monomer_name', models.CharField(max_length=250)),
                ('monomer_LG', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SynthMutations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='T_RNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tRNA_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Synthetase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synth_common_name', models.CharField(max_length=100)),
                ('accession_id', models.CharField(max_length=50)),
                ('pbd_id', models.CharField(max_length=10)),
                ('mutations', models.ManyToManyField(related_name='mutations', to='base.SynthMutations')),
                ('organism_id', models.ManyToManyField(related_name='organisms', to='base.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOI', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('authors', models.ManyToManyField(related_name='authors', to='base.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ribosome_name', models.CharField(max_length=50)),
                ('n_term_incorporation', models.CharField(max_length=5, null=True)),
                ('internal_incorporation', models.CharField(max_length=5, null=True)),
                ('rib_readout', models.CharField(choices=[('LC', 'LC-MS'), ('SD', 'SDS-PAGE'), ('GF', 'GFP Fluorescence'), ('PE', 'Protein Expression')], max_length=2, null=True)),
                ('rib_incorporation_notes', models.TextField(null=True)),
                ('reaction_yield', models.FloatField(null=True)),
                ('reaction_Kcat', models.FloatField(null=True)),
                ('reaction_Km', models.FloatField(null=True)),
                ('flexizyme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.flexizyme')),
                ('monomer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.monomer')),
                ('reference', models.ManyToManyField(related_name='references', to='base.Reference')),
                ('synthetase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.synthetase')),
                ('tRNA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.t_rna')),
            ],
        ),
        migrations.CreateModel(
            name='MicrohelixAssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField()),
                ('acylation_yield', models.FloatField(null=True)),
                ('assay_notes', models.TextField()),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.reaction')),
            ],
        ),
    ]
