# Generated by Django 4.0.2 on 2022-02-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexizyme',
            name='flex_sequence',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monomer',
            name='monomer_smiles',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='t_rna',
            name='tRNA_seq',
            field=models.TextField(null=True),
        ),
    ]
