# Generated by Django 4.0.2 on 2022-04-21 08:25

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOI', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=250)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, default='', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ribosome_name', models.CharField(max_length=50)),
                ('n_term_incorporation', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=1)),
                ('n_term_percent', models.FloatField(blank=True, null=True)),
                ('internal_incorporation', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=1)),
                ('internal_percent', models.FloatField(blank=True, null=True)),
                ('rib_readout', models.CharField(blank=True, default='', max_length=30)),
                ('rib_incorporation_notes', models.TextField(blank=True, default='')),
                ('reaction_yield', models.FloatField(blank=True, null=True)),
                ('reaction_Kcat', models.FloatField(blank=True, null=True)),
                ('reaction_Km', models.FloatField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('assay', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaction', to='base.microhelixassay')),
                ('flexizyme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='base.flexizyme')),
                ('monomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='base.monomer')),
                ('references', models.ManyToManyField(related_name='reactions', to='base.Reference')),
                ('synthetase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='base.synthetase')),
                ('tRNA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.t_rna')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
