# Generated by Django 4.0.2 on 2022-04-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organism',
            constraint=models.UniqueConstraint(fields=('organism_name', 'id'), name='unique organism'),
        ),
        migrations.AddConstraint(
            model_name='synthmutations',
            constraint=models.UniqueConstraint(fields=('id', 'mutation_name'), name='unique mutations'),
        ),
    ]
