# Generated by Django 4.0.2 on 2022-05-24 10:12

from django.db import migrations
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monomer',
            name='molecule',
            field=django_rdkit.models.fields.MolField(null=True),
        ),
    ]
