# Generated by Django 4.0.2 on 2022-04-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_reaction_references_delete_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOI', models.TextField(max_length=50)),
                ('title', models.TextField(blank=True, default='')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, default='', max_length=75)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='reaction',
            name='references',
            field=models.ManyToManyField(related_name='reactions', to='base.Reference'),
        ),
    ]
