# Generated by Django 4.0.2 on 2022-04-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_organism_unique organism_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organism',
            name='unique organism',
        ),
        migrations.RemoveConstraint(
            model_name='synthmutations',
            name='unique mutations',
        ),
        migrations.AlterField(
            model_name='organism',
            name='organism_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='synthmutations',
            name='mutation_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
