# Generated by Django 4.0.2 on 2022-04-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_reaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flexizyme',
            constraint=models.UniqueConstraint(fields=('flex_name', 'flex_sequence'), name='unique flexizyme name'),
        ),
    ]
