# Generated by Django 4.0.2 on 2022-07-08 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reactiondraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged', models.BooleanField(verbose_name='is flagged')),
            ],
        ),
        migrations.AddField(
            model_name='reaction',
            name='flag',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.flag'),
            preserve_default=False,
        ),
    ]
