# Generated by Django 4.0.2 on 2022-05-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_monomer_molecule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monomer',
            name='molecule',
        ),
    ]
