# Generated by Django 4.0.2 on 2022-02-04 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_flexizyme_flex_sequence_monomer_monomer_smiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='flexizyme',
            name='flex_sequence',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='microhelixassay',
            name='acylation_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monomer',
            name='monomer_LG',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='monomer',
            name='monomer_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='monomer',
            name='monomer_smiles',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='flexizyme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.flexizyme'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='internal_incorporation',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='n_term_incorporation',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_Kcat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_Km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='rib_incorporation_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='rib_readout',
            field=models.CharField(blank=True, choices=[('LC', 'LC-MS'), ('SD', 'SDS-PAGE'), ('GF', 'GFP Fluorescence'), ('PE', 'Protein Expression')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='synthetase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.synthetase'),
        ),
        migrations.AlterField(
            model_name='synthetase',
            name='accession_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='synthetase',
            name='mutations',
            field=models.ManyToManyField(blank=True, related_name='mutations', to='base.SynthMutations'),
        ),
        migrations.AlterField(
            model_name='synthetase',
            name='organism_id',
            field=models.ManyToManyField(blank=True, related_name='organisms', to='base.Organism'),
        ),
        migrations.AlterField(
            model_name='synthetase',
            name='pbd_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='t_rna',
            name='tRNA_seq',
            field=models.TextField(blank=True, default=''),
        ),
    ]
