# Generated by Django 4.0.2 on 2022-04-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_flexizyme_unique flexizyme name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.UniqueConstraint(fields=('DOI', 'title', 'journal'), name='unique reference'),
        ),
    ]
