# Generated by Django 4.0.2 on 2022-02-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microhelixassay',
            name='assay_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='microhelixassay',
            name='conditions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
