# Generated by Django 4.0.2 on 2022-04-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_organism_unique organism_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='organism_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='synthmutations',
            name='mutation_name',
            field=models.CharField(max_length=25),
        ),
    ]
