# Generated by Django 4.0.2 on 2022-04-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_reference_delete_author_reaction_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
