# Generated by Django 4.0.2 on 2022-04-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_organism_organism_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parentsynth',
            name='unique parent',
        ),
        migrations.RemoveConstraint(
            model_name='synthetase',
            name='unique synthetase',
        ),
        migrations.AlterField(
            model_name='parentsynth',
            name='parent_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='synthetase',
            name='synth_common_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
