# Generated by Django 4.0.2 on 2022-07-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_flag_reaction_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='flagged',
            field=models.BooleanField(null=True, verbose_name='is flagged'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='is_flagged',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.flag'),
        ),
    ]
