# Generated by Django 4.0.2 on 2022-04-22 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_reference_unique reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentSynth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=50)),
                ('pbd_id', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='synthetase',
            name='pbd_id',
        ),
        migrations.AddConstraint(
            model_name='synthetase',
            constraint=models.UniqueConstraint(fields=('synth_common_name',), name='unique synthetase'),
        ),
        migrations.AlterField(
            model_name='synthetase',
            name='parent_synthetase',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.parentsynth'),
        ),
    ]
