# Generated by Django 4.0.2 on 2022-02-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_reaction_n_term_incorporation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='internal_incorporation',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('P', models.FloatField())], default='', max_length=1),
        ),
    ]
