# Generated by Django 4.0.2 on 2022-04-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_parentsynth_unique parent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flexizyme',
            name='unique flexizyme name',
        ),
        migrations.RemoveConstraint(
            model_name='reference',
            name='unique reference',
        ),
        migrations.AlterField(
            model_name='parentsynth',
            name='parent_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='synthetase',
            name='synth_common_name',
            field=models.CharField(max_length=100),
        ),
    ]
