# Generated by Django 4.0.2 on 2022-07-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_flag_flagged_alter_reaction_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='flagged',
            field=models.BooleanField(default=None, verbose_name='is flagged'),
            preserve_default=False,
        ),
    ]
