# Generated by Django 4.0.2 on 2022-04-22 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_parentsynth_remove_synthetase_pbd_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synthetase',
            name='parent_synthetase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.parentsynth'),
        ),
    ]
