# Generated by Django 4.0.2 on 2022-02-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_reaction_internal_incorporation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='flexizyme',
            name='flex_sequence',
            field=models.TextField(blank=True, default=''),
        ),
    ]
