# Generated by Django 4.0.2 on 2022-04-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_synthetase_parent_synthetase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentsynth',
            old_name='pbd_id',
            new_name='parent_pbd_id',
        ),
        migrations.AddField(
            model_name='synthetase',
            name='pbd_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
