# Generated by Django 4.0.2 on 2022-07-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_flag_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='flagged',
            field=models.BooleanField(null=True, verbose_name='is flagged'),
        ),
    ]
