# Generated by Django 4.0.2 on 2022-04-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_flexizyme_unique flexizyme name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='organism_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parentsynth',
            name='parent_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='DOI',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='synthmutations',
            name='mutation_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
