# Generated by Django 4.0.2 on 2022-02-04 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_reaction_date_added_reference_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microhelixassay',
            name='reaction',
        ),
        migrations.AddField(
            model_name='reaction',
            name='assay',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.microhelixassay'),
        ),
    ]
