# Generated by Django 4.0.2 on 2022-07-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_flag_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='message',
            field=models.TextField(null=True, verbose_name='message'),
        ),
    ]
