# Generated by Django 4.0.2 on 2022-04-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_pbd_id_parentsynth_parent_pbd_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='synthetase',
            name='unique synthetase',
        ),
        migrations.AddConstraint(
            model_name='parentsynth',
            constraint=models.UniqueConstraint(fields=('parent_name', 'parent_pbd_id'), name='unique parent'),
        ),
        migrations.AddConstraint(
            model_name='synthetase',
            constraint=models.UniqueConstraint(fields=('synth_common_name', 'accession_id'), name='unique synthetase'),
        ),
    ]
