# Generated by Django 4.0.2 on 2022-04-22 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_synthetase_unique synthetase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synthetase',
            name='parent_synthetase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.parentsynth'),
            preserve_default=False,
        ),
    ]
