# Generated by Django 4.0.2 on 2022-02-04 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_reaction_assay_microhelixassay_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microhelixassay',
            name='reaction',
        ),
        migrations.AddField(
            model_name='reaction',
            name='assay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.microhelixassay'),
        ),
    ]
