# Generated by Django 4.0.2 on 2022-02-08 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_microhelixassay_reaction_reaction_assay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexizyme',
            name='id',
        ),
        migrations.AlterField(
            model_name='flexizyme',
            name='flex_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='assay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaction', to='base.microhelixassay'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='monomer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to='base.monomer'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reference',
            field=models.ManyToManyField(related_name='reactions', to='base.Reference'),
        ),
    ]
