# Generated by Django 4.0.2 on 2022-02-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_flexizyme_id_alter_flexizyme_flex_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='reference',
            new_name='references',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='flexizyme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to='base.flexizyme'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='synthetase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to='base.synthetase'),
        ),
    ]
