# Generated by Django 4.0.2 on 2022-02-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_reference_reaction_references_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexizyme',
            name='flex_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='flexizyme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='base.flexizyme'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='synthetase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='base.synthetase'),
        ),
    ]
