# Generated by Django 4.0.2 on 2022-02-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_flexizyme_id_alter_flexizyme_flex_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexizyme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
