# Generated by Django 4.0.2 on 2022-02-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_flexizyme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='internal_incorporation',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('P', models.FloatField())], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='authors',
            field=models.ManyToManyField(related_name='references', to='base.Author'),
        ),
        migrations.AlterField(
            model_name='synthetase',
            name='mutations',
            field=models.ManyToManyField(blank=True, related_name='synthetases', to='base.SynthMutations'),
        ),
        migrations.AlterField(
            model_name='synthetase',
            name='organism_id',
            field=models.ManyToManyField(blank=True, related_name='synthetases', to='base.Organism'),
        ),
    ]
