# Generated by Django 4.0.2 on 2022-02-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_organism_id_synthetase_organisms'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthetase',
            name='parent_synthetase',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
