# Generated by Django 4.0.2 on 2022-02-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_synthetase_parent_synthetase'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='internal_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reaction',
            name='n_term_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='journal',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='internal_incorporation',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('A', 'Not tested')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='n_term_incorporation',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('A', 'Not tested')], default='', max_length=1),
        ),
    ]
