# Generated by Django 4.0.2 on 2022-02-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_reaction_internal_percent_reaction_n_term_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentSynth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='synthetase',
            name='parent_synthetase',
        ),
    ]
