# Generated by Django 4.0.2 on 2022-02-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_parentsynth_remove_synthetase_parent_synthetase'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthetase',
            name='parent_synthetase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_synthetases', to='base.parentsynth'),
        ),
    ]
