# Generated by Django 4.0.2 on 2022-03-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_synthetase_parent_synthetase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='reaction',
            name='internal_incorporation',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('A', 'Not tested')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='monomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='base.monomer'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='n_term_incorporation',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('A', 'Not tested')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='synthetase',
            name='parent_synthetase',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ParentSynth',
        ),
    ]
