# Generated by Django 4.0.2 on 2022-04-11 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_reaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='flexizyme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='base.flexizyme'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='internal_incorporation',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='n_term_incorporation',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='rib_readout',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='synthetase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='base.synthetase'),
        ),
    ]
