# Generated by Django 4.0.2 on 2022-04-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_reaction_flexizyme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='references', to='base.Author'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publication_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
