# Generated by Django 4.0.2 on 2022-04-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_reference_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
